import{S as g,i as c}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))h(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&h(n)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function h(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const y="https://pixabay.com/api/",v="45091921-bafbe55c990439d7032dec8c8";async function L(e,o=1){try{return(await axios.get(y,{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}catch(r){throw iziToast.error("Error fetching images:",r),r}}const p=document.querySelector(".gallery-list"),w=new g(".gallery-list a",{captions:!0,captionsData:"alt",captionsDelay:250});function x(e){let o=e.hits.map(r=>`<div class="image-wrapper">
    <a href="${r.largeImageURL}">
    <img class="gallery-img" src="${r.webformatURL}" alt="${r.tags}"></img>
    </a>
    <div class="text-gallery">
    <div class="text-item"><h5 class="text-header">Likes</h5><p class="text-paragraph">${r.likes}</p></div>
    <div class="text-item"><h5 class="text-header">Views</h5><p class="text-paragraph">${r.views}</p></div>
    <div class="text-item"><h5 class="text-header">Comments</h5><p class="text-paragraph">${r.comments}</p></div>
    <div class="text-item"><h5 class="text-header">Downloads</h5><p class="text-paragraph">${r.downloads}</p></div>
    </div>
    </div>`).join("");p.insertAdjacentHTML("beforeend",o),w.refresh()}function b(){p.innerHTML=""}const m=document.querySelector(".form-gallery"),S=document.querySelector(".form-gallery-input"),l=document.querySelector(".loader"),d=document.querySelector(".load-more"),a=document.querySelector(".scroll-to-top");let i=1,u="";m.addEventListener("submit",T);d.addEventListener("click",q);a.addEventListener("click",P);async function T(e){e.preventDefault(),b(),l.classList.remove("hidden"),u=S.value.trim(),i=1,await f(),m.reset()}async function q(){i+=1,await f()}async function f(){try{const e=await L(u,i);if(l.classList.add("hidden"),e.total===0||u===""){c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}x(e),e.hits.length===0||i*15>=e.totalHits?(d.classList.add("hidden"),c.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):d.classList.remove("hidden"),E(),$()}catch(e){c.error(e),l.classList.add("hidden")}}function E(){const{height:e}=document.querySelector(".gallery-list").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function $(){window.scrollY>1e3?a.classList.remove("hidden"):a.classList.add("hidden")}function P(){window.scrollTo({top:0,behavior:"auto"})}window.addEventListener("scroll",a);
//# sourceMappingURL=commonHelpers.js.map
